; PlatformIO Configuration for AbelhaAlerta-ESC2026
; Plataforma: Raspberry Pi Pico (RP2040) / BigDog Lab

[env:abelhaalerta]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
monitor_speed = 115200

; Bibliotecas
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5

; Flags de compilação
build_flags =
    -DPICO_BOARD=pico
    -DUSE_TINYUSB=0
